package codacy.codesniffer.docsgen

object DefaultPatterns {

  // The list of defaults was retrieved from PHPCS config file:
  // https://github.com/squizlabs/PHP_CodeSniffer/blob/master/phpcs.xml.dist
  val list = List("PEAR_Classes_ClassDeclaration",
                  "PEAR_Commenting_FunctionComment",
                  "PEAR_ControlStructures_ControlSignature",
                  "PEAR_ControlStructures_MultiLineCondition",
                  "PEAR_Files_IncludingFile",
                  "PEAR_Formatting_MultiLineAssignment",
                  "PEAR_Functions_FunctionCallSignature",
                  "PEAR_Functions_FunctionDeclaration",
                  "PEAR_Functions_ValidDefaultValue",
                  "PEAR_NamingConventions_ValidClassName",
                  "PEAR_WhiteSpace_ObjectOperatorIndent",
                  "PEAR_WhiteSpace_ScopeClosingBrace",
                  "PEAR_WhiteSpace_ScopeIndent",
                  "Squiz_Arrays_ArrayBracketSpacing",
                  "Squiz_Arrays_ArrayDeclaration",
                  "Squiz_Commenting_ClosingDeclarationComment",
                  "Squiz_ControlStructures_ControlSignature",
                  "Squiz_ControlStructures_ElseIfDeclaration",
                  "Squiz_Commenting_BlockComment",
                  "Squiz_Commenting_DocCommentAlignment",
                  "Squiz_Commenting_EmptyCatchComment",
                  "Squiz_Commenting_InlineComment",
                  "Squiz_Commenting_LongConditionClosingComment",
                  "Squiz_Commenting_PostStatementComment",
                  "Squiz_Commenting_VariableComment",
                  "Squiz_Formatting_OperatorBracket",
                  "Squiz_Functions_FunctionDeclarationArgumentSpacing",
                  "Squiz_Operators_ComparisonOperatorUsage",
                  "Squiz_PHP_DisallowInlineIf",
                  "Squiz_Scope_MethodScope",
                  "Squiz_Strings_ConcatenationSpacing",
                  "Squiz_WhiteSpace_ControlStructureSpacing",
                  "Squiz_WhiteSpace_FunctionClosingBraceSpace",
                  "Squiz_WhiteSpace_FunctionSpacing",
                  "Squiz_WhiteSpace_MemberVarSpacing",
                  "Squiz_WhiteSpace_OperatorSpacing",
                  "Squiz_WhiteSpace_SuperfluousWhitespace",
                  "Generic_Arrays_DisallowLongArraySyntax",
                  "Generic_Commenting_Todo",
                  "Generic_ControlStructures_DisallowYodaConditions",
                  "Generic_ControlStructures_InlineControlStructure",
                  "Generic_Formatting_DisallowMultipleStatements",
                  "Generic_Formatting_SpaceAfterCast",
                  "Generic_NamingConventions_ConstructorName",
                  "Generic_PHP_DeprecatedFunctions",
                  "Generic_PHP_LowerCaseKeyword",
                  "Generic_Strings_UnnecessaryStringConcat",
                  "Generic_WhiteSpace_IncrementDecrementSpacing",
                  "PSR2_Classes_PropertyDeclaration",
                  "PSR2_Methods_MethodDeclaration",
                  "PSR2_Files_EndFileNewline",
                  "PSR12_Files_OpenTag",
                  "Zend_Files_ClosingTag",
                  "MEQP1_Security_Acl",
                  "MEQP1_Security_DiscouragedFunction",
                  "MEQP1_Security_IncludeFile",
                  "MEQP1_Security_LanguageConstruct",
                  "MEQP1_Security_Superglobal",
                  "WordPress_DB_PreparedSQL",
                  "WordPress_Security_EscapeOutput",
                  "WordPress_Security_NonceVerification",
                  "WordPress_Security_PluginMenuSlug",
                  "WordPress_Security_SafeRedirect",
                  "WordPress_Security_ValidatedSanitizedInput")
}
